name: Build and Deploy Docker to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: app-mentori-ia-prod
  ACR_NAME: acrmentoriaiaprod
  IMAGE_NAME: backend-mentoria

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login no ACR
        run: az acr login --name ${{ env.ACR_NAME }}

      - name: Build e Push da Imagem Docker
        run: |
        
          docker build -t ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} -f backend/Dockerfile backend/
          
          
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
          
          docker tag ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest

      - name: Configurar Variáveis de Ambiente
        run: |
          az webapp config appsettings set \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --resource-group "${{ secrets.AZURE_RESOURCE_GROUP }}" \
            --settings \
              SPRING_PROFILES_ACTIVE="prod" \
              SPRING_DATASOURCE_URL="${{ secrets.SPRING_DATASOURCE_URL }}" \
              SPRING_DATASOURCE_USERNAME="${{ secrets.SPRING_DATASOURCE_USERNAME }}" \
              SPRING_DATASOURCE_PASSWORD="${{ secrets.SPRING_DATASOURCE_PASSWORD }}" \
              API_SECURITY_TOKEN_SECRET="${{ secrets.API_SECURITY_TOKEN_SECRET }}" \
              OPENAI_KEY="${{ secrets.OPENAI_KEY }}" \
              GOOGLE_ID="${{ secrets.GOOGLE_ID }}" \
              GOOGLE_SECRET="${{ secrets.GOOGLE_SECRET }}" \
              WEBSITES_PORT=8080

      - name: Deploy no Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          images: ${{ env.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Logout
        run: az logout